#!/bin/bash

#Dépôt Git SigmaHQ
wget -O sigma.zip https://github.com/SigmaHQ/sigma/archive/refs/heads/master.zip

#Décompression de l'archive sigma
unzip sigma.zip

rules_set_auditd=(

lnx_auditd_auditing_config_change.yml
# lnx_auditd_binary_padding.yml
# lnx_auditd_capabilities_discovery.yml
# lnx_auditd_change_file_time_attr.yml
lnx_auditd_coinminer.yml
# lnx_auditd_create_account.yml
lnx_auditd_data_compressed.yml
lnx_auditd_data_exfil_wget.yml
lnx_auditd_disable_system_firewall.yml
# lnx_auditd_file_or_folder_permissions.yml
# lnx_auditd_find_cred_in_files.yml 
lnx_auditd_hidden_binary_execution.yml
# lnx_auditd_hidden_files_directories.yml
# lnx_auditd_keylogging_with_pam_d.yml
# lnx_auditd_ld_so_preload_mod.yml
# lnx_auditd_logging_config_change.yml
# lnx_auditd_masquerading_crond.yml
# lnx_auditd_modify_system_firewall.yml
# lnx_auditd_network_service_scanning.yml
# lnx_auditd_network_sniffing.yml
# lnx_auditd_omigod_scx_runasprovider_executeshellcommand.yml
# lnx_auditd_password_policy_discovery.yml
# lnx_auditd_pers_systemd_reload.yml
# lnx_auditd_screencapture_import.yml
# lnx_auditd_screencaputre_xwd.yml
# lnx_auditd_split_file_into_pieces.yml
# lnx_auditd_steghide_embed_steganography.yml
# lnx_auditd_steghide_extract_steganography.yml
# lnx_auditd_susp_c2_commands.yml
# lnx_auditd_susp_cmds.yml
# lnx_auditd_susp_exe_folders.yml
# lnx_auditd_susp_histfile_operations.yml
# lnx_auditd_systemd_service_creation.yml
# lnx_auditd_system_info_discovery2.yml
# lnx_auditd_system_info_discovery.yml
# lnx_auditd_system_shutdown_reboot.yml
# lnx_auditd_unix_shell_configuration_modification.yml
# lnx_auditd_unzip_hidden_zip_files_steganography.yml
# lnx_auditd_user_discovery.yml
# lnx_auditd_web_rce.yml

)

# Installation sigma-cli
python3 -m pip install sigma-cli

#convertir chaque règle avec sigma-cli pour Splunk
for rule in ${rules_set_auditd[@]}; do
   sigma convert --without-pipeline -t splunk -f default sigma-master/rules/linux/auditd/$rule > /home/sp1der/Github/splunk_rules/$rule.txt
done
